import os
import glob
from unittest import loader
from xml.parsers.expat import model
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import cv2
from skimage.metrics import peak_signal_noise_ratio, structural_similarity
import matplotlib.pyplot as plt
from tqdm import tqdm

# ========== CHANGE ONLY THIS PATH ==========
DATA_ROOT = "Ir"   # <-- Replace with the full path to your 'Ir' folder
# ===========================================

SAVE_DIR = "./checkpoints_hat"
ERROR_MAP_DIR = "./error_maps_hat"
BATCH_SIZE = 8
EPOCHS = 200
LR = 1e-4
SCALE = 4                     # upscaling factor (2,3,4)
USE_EDGE_LOSS = True
EDGE_LOSS_WEIGHT = 0.6
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ------------------------------
# Dataset: uses LR images from the single folder.
# HR images are generated by bicubic upsampling of the LR images.
# ------------------------------
class SingleFolderDataset(Dataset):
    def __init__(self, folder_path, scale=4, patch_size=192):
        self.folder_path = folder_path
        self.scale = scale
        self.patch_size = patch_size
        # Collect all image files
        self.image_paths = []
        for ext in ['*.png', '*.jpg', '*.jpeg', '*.bmp', '*.tif', '*.tiff']:
            self.image_paths.extend(glob.glob(os.path.join(folder_path, ext)))
            self.image_paths.extend(glob.glob(os.path.join(folder_path, '**', ext), recursive=True))
        if len(self.image_paths) == 0:
            raise ValueError(f"No images found in {folder_path}")
        print(f"Found {len(self.image_paths)} LR images. HR will be created by bicubic upscaling.")

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        lr_path = self.image_paths[idx]
        lr_img = cv2.imread(lr_path, cv2.IMREAD_COLOR)
        if lr_img is None:
            raise IOError(f"Cannot read {lr_path}")
        lr_img = cv2.cvtColor(lr_img, cv2.COLOR_BGR2RGB)
        # LR tensor [0,1]
        lr_tensor = torch.from_numpy(lr_img).float().permute(2,0,1) / 255.0

        # Create HR by bicubic upsampling (simulates ground truth)
        h, w = lr_img.shape[:2]
        hr_h, hr_w = h * self.scale, w * self.scale
        hr_img = cv2.resize(lr_img, (hr_w, hr_h), interpolation=cv2.INTER_CUBIC)
        hr_tensor = torch.from_numpy(hr_img).float().permute(2,0,1) / 255.0

        # Optional random crop
        if self.patch_size:
            _, h_hr, w_hr = hr_tensor.shape
            if h_hr > self.patch_size and w_hr > self.patch_size:
                top = torch.randint(0, h_hr - self.patch_size, (1,)).item()
                left = torch.randint(0, w_hr - self.patch_size, (1,)).item()
                hr_tensor = hr_tensor[:, top:top+self.patch_size, left:left+self.patch_size]
                lr_tensor = lr_tensor[:, top//self.scale:top//self.scale+self.patch_size//self.scale,
                                      left//self.scale:left//self.scale+self.patch_size//self.scale]
        return lr_tensor, hr_tensor

# ------------------------------
# HAT Model (simplified but effective)
# ------------------------------
class ChannelAttention(nn.Module):
    def __init__(self, channels, reduction=16):
        super().__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.fc = nn.Sequential(
            nn.Linear(channels, channels // reduction),
            nn.ReLU(inplace=True),
            nn.Linear(channels // reduction, channels),
            nn.Sigmoid()
        )
    def forward(self, x):
        b, c, _, _ = x.size()
        y = self.avg_pool(x).view(b, c)
        y = self.fc(y).view(b, c, 1, 1)
        return x * y

class SpatialAttention(nn.Module):
    def __init__(self, kernel_size=7):
        super().__init__()
        self.conv = nn.Conv2d(2, 1, kernel_size, padding=kernel_size//2, bias=False)
        self.sigmoid = nn.Sigmoid()
    def forward(self, x):
        avg_out = torch.mean(x, dim=1, keepdim=True)
        max_out, _ = torch.max(x, dim=1, keepdim=True)
        y = torch.cat([avg_out, max_out], dim=1)
        y = self.conv(y)
        return x * self.sigmoid(y)

class HATBlock(nn.Module):
    def __init__(self, channels, reduction=16):
        super().__init__()
        self.conv1 = nn.Conv2d(channels, channels, 3, padding=1)
        self.relu = nn.ReLU(inplace=True)
        self.conv2 = nn.Conv2d(channels, channels, 3, padding=1)
        self.ca = ChannelAttention(channels, reduction)
        self.sa = SpatialAttention()
    def forward(self, x):
        residual = x
        out = self.conv1(x)
        out = self.relu(out)
        out = self.conv2(out)
        out = self.ca(out)
        out = self.sa(out)
        return out + residual

class HAT(nn.Module):
    def __init__(self, scale=4, in_ch=3, out_ch=3, num_blocks=8, channels=64):
        super().__init__()
        self.scale = scale
        self.conv_first = nn.Conv2d(in_ch, channels, 3, padding=1)
        self.body = nn.Sequential(*[HATBlock(channels) for _ in range(num_blocks)])
        self.conv_last = nn.Conv2d(channels, out_ch * (scale**2), 3, padding=1)
        self.pixel_shuffle = nn.PixelShuffle(scale)
    def forward(self, x):
        x = self.conv_first(x)
        identity = x
        out = self.body(x)
        out = out + identity
        out = self.conv_last(out)
        out = self.pixel_shuffle(out)
        return out

# ------------------------------
# Edge Loss
# ------------------------------
class EdgeLoss(nn.Module):
    def __init__(self):
        super().__init__()
        sobel_x = torch.tensor([[-1,0,1],[-2,0,2],[-1,0,1]], dtype=torch.float32).view(1,1,3,3)
        sobel_y = torch.tensor([[-1,-2,-1],[0,0,0],[1,2,1]], dtype=torch.float32).view(1,1,3,3)
        self.register_buffer('sobel_x', sobel_x)
        self.register_buffer('sobel_y', sobel_y)

    def rgb_to_grayscale(self, img):
        # img: [B,3,H,W] in [0,1]
        weights = torch.tensor([0.299, 0.587, 0.114], device=img.device).view(1,3,1,1)
        return torch.sum(img * weights, dim=1, keepdim=True)  # [B,1,H,W]

    def forward(self, pred, target):
        pred_gray = self.rgb_to_grayscale(pred)
        target_gray = self.rgb_to_grayscale(target)

        grad_pred_x = torch.abs(torch.nn.functional.conv2d(pred_gray, self.sobel_x, padding=1))
        grad_pred_y = torch.abs(torch.nn.functional.conv2d(pred_gray, self.sobel_y, padding=1))
        grad_target_x = torch.abs(torch.nn.functional.conv2d(target_gray, self.sobel_x, padding=1))
        grad_target_y = torch.abs(torch.nn.functional.conv2d(target_gray, self.sobel_y, padding=1))

        loss = torch.mean(torch.abs(grad_pred_x - grad_target_x)) + \
               torch.mean(torch.abs(grad_pred_y - grad_target_y))
        return loss
# ------------------------------
# Training
# ------------------------------
def train():
    os.makedirs(SAVE_DIR, exist_ok=True)
    os.makedirs(ERROR_MAP_DIR, exist_ok=True)

    dataset = SingleFolderDataset(DATA_ROOT, scale=SCALE)
    loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=2)

    model = HAT(scale=SCALE).to(DEVICE)
    optimizer = optim.Adam(model.parameters(), lr=LR)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS, eta_min=1e-6)
    l1_loss = nn.L1Loss()
    edge_loss = EdgeLoss().to(DEVICE)   # <-- ADD .to(DEVICE)

    best_psnr = 0.0
    for epoch in range(1, EPOCHS+1):
        model.train()
        epoch_loss = 0.0
        pbar = tqdm(loader, desc=f"Epoch {epoch}/{EPOCHS}")
        for lr, hr in pbar:
            lr, hr = lr.to(DEVICE), hr.to(DEVICE)
            sr = model(lr)
            loss_l1 = l1_loss(sr, hr)
            if USE_EDGE_LOSS:
                loss_edge = edge_loss(sr, hr)
                loss = loss_l1 + EDGE_LOSS_WEIGHT * loss_edge
            else:
                loss = loss_l1
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()
            pbar.set_postfix({"Loss": f"{loss.item():.4f}"})
        scheduler.step()

        if epoch % 5 == 0 or epoch == EPOCHS:
            psnr, ssim = validate(model, dataset)
            print(f"Epoch {epoch}: Val PSNR = {psnr:.2f} dB, SSIM = {ssim:.4f}")
            if psnr > best_psnr:
                best_psnr = psnr
                torch.save(model.state_dict(), os.path.join(SAVE_DIR, "best_hat.pth"))
                print("  -> Best model saved.")

    print(f"Training completed. Best PSNR: {best_psnr:.2f} dB")

def validate(model, dataset, save_error_maps=True):
    model.eval()
    psnr_list = []
    ssim_list = []
    with torch.no_grad():
        for idx in range(len(dataset)):
            lr, hr = dataset[idx]
            lr = lr.unsqueeze(0).to(DEVICE)
            hr = hr.unsqueeze(0).to(DEVICE)
            sr = model(lr)
            sr_np = sr.squeeze(0).cpu().numpy().transpose(1,2,0)
            hr_np = hr.squeeze(0).cpu().numpy().transpose(1,2,0)
            sr_np = np.clip(sr_np, 0, 1)
            hr_np = np.clip(hr_np, 0, 1)
            psnr = peak_signal_noise_ratio(hr_np, sr_np, data_range=1)
            ssim = structural_similarity(hr_np, sr_np, multichannel=True, channel_axis=2, data_range=1)
            psnr_list.append(psnr)
            ssim_list.append(ssim)

            if save_error_maps:
                error = np.abs(sr_np - hr_np).mean(axis=2)
                plt.figure(figsize=(6,5))
                plt.imshow(error, cmap='hot', vmin=0, vmax=0.1)
                plt.colorbar(label='Absolute Error')
                plt.title(f'Error Map - Image {idx}')
                plt.axis('off')
                plt.savefig(os.path.join(ERROR_MAP_DIR, f"error_{idx}.png"), bbox_inches='tight', dpi=150)
                plt.close()
    return np.mean(psnr_list), np.mean(ssim_list)

if __name__ == "__main__":
    train()