{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "88f07614",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "# %%\n",
    "# Cell 1: Imports and device setup\n",
    "import os\n",
    "import cv2\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "from torchvision.transforms import ToTensor\n",
    "from skimage.metrics import peak_signal_noise_ratio, structural_similarity\n",
    "\n",
    "# Check if CUDA is available and set device\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f\"Using device: {device}\")\n",
    "\n",
    "# %%\n",
    "# Cell 2: Dataset definition\n",
    "class InfraredDataset(Dataset):\n",
    "    def __init__(self, folder, scale=4, crop_size=512):\n",
    "        self.all_files = [os.path.join(folder, f) for f in os.listdir(folder)\n",
    "                      if f.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp'))]\n",
    "        self.files = [f for f in self.all_files if cv2.imread(f, cv2.IMREAD_GRAYSCALE) is not None]\n",
    "        self.scale = scale\n",
    "        self.crop_size = crop_size\n",
    "        self.transform = ToTensor()\n",
    "\n",
    "        # Check for invalid images\n",
    "        for f in self.all_files:\n",
    "            if f not in self.files:\n",
    "                print(f\"Skipping invalid image: {f}\")\n",
    "\n",
    "    def __len__(self):\n",
    "        return len(self.files)\n",
    "\n",
    "    def __getitem__(self, idx):\n",
    "        img = cv2.imread(self.files[idx], cv2.IMREAD_GRAYSCALE)\n",
    "        if img is None:\n",
    "            # Just in case, skip and pick another image\n",
    "            idx = (idx + 1) % len(self.files)\n",
    "            img = cv2.imread(self.files[idx], cv2.IMREAD_GRAYSCALE)\n",
    "        \n",
    "        # Center crop or resize\n",
    "        h, w = img.shape\n",
    "        if h < self.crop_size or w < self.crop_size:\n",
    "            img = cv2.resize(img, (self.crop_size, self.crop_size), interpolation=cv2.INTER_CUBIC)\n",
    "        else:\n",
    "            top = (h - self.crop_size) // 2\n",
    "            left = (w - self.crop_size) // 2\n",
    "            img = img[top:top+self.crop_size, left:left+self.crop_size]\n",
    "        \n",
    "        hr = self.transform(img)\n",
    "        \n",
    "        # Downsample for LR\n",
    "        lr_img = cv2.resize(img, (self.crop_size // self.scale, self.crop_size // self.scale), \n",
    "                           interpolation=cv2.INTER_CUBIC)\n",
    "        lr_img = cv2.resize(lr_img, (self.crop_size, self.crop_size), \n",
    "                           interpolation=cv2.INTER_CUBIC)\n",
    "        lr = self.transform(lr_img)\n",
    "        \n",
    "        return lr, hr\n",
    "\n",
    "# %%\n",
    "# Cell 3: SRCNN Model definition\n",
    "class SRCNN(nn.Module):\n",
    "    def __init__(self):\n",
    "        super(SRCNN, self).__init__()\n",
    "        self.layer1 = nn.Conv2d(1, 64, kernel_size=9, padding=4)\n",
    "        self.layer2 = nn.Conv2d(64, 32, kernel_size=5, padding=2)\n",
    "        self.layer3 = nn.Conv2d(32, 1, kernel_size=5, padding=2)\n",
    "        self.relu = nn.ReLU(inplace=True)\n",
    "\n",
    "    def forward(self, x):\n",
    "        x = self.relu(self.layer1(x))\n",
    "        x = self.relu(self.layer2(x))\n",
    "        x = self.layer3(x)\n",
    "        return x\n",
    "\n",
    "# %%\n",
    "# Cell 4: EDSR Model definition\n",
    "class ResidualBlock(nn.Module):\n",
    "    def __init__(self, channels):\n",
    "        super().__init__()\n",
    "        self.conv1 = nn.Conv2d(channels, channels, 3, padding=1)\n",
    "        self.relu = nn.ReLU(inplace=True)\n",
    "        self.conv2 = nn.Conv2d(channels, channels, 3, padding=1)\n",
    "\n",
    "    def forward(self, x):\n",
    "        residual = x\n",
    "        out = self.relu(self.conv1(x))\n",
    "        out = self.conv2(out)\n",
    "        out += residual\n",
    "        return out\n",
    "\n",
    "class EDSR(nn.Module):\n",
    "    def __init__(self, num_blocks=8, channels=64, scale=2):\n",
    "        super().__init__()\n",
    "        self.conv1 = nn.Conv2d(1, channels, 3, padding=1)\n",
    "        self.res_blocks = nn.Sequential(*[ResidualBlock(channels) for _ in range(num_blocks)])\n",
    "        self.conv2 = nn.Conv2d(channels, channels, 3, padding=1)\n",
    "        # Upsampling\n",
    "        self.upsample = nn.Sequential(\n",
    "            nn.Conv2d(channels, channels * scale * scale, 3, padding=1),\n",
    "            nn.PixelShuffle(scale),\n",
    "            nn.Conv2d(channels, 1, 3, padding=1)\n",
    "        )\n",
    "\n",
    "    def forward(self, x):\n",
    "        x = self.conv1(x)\n",
    "        x = self.res_blocks(x)\n",
    "        x = self.conv2(x)\n",
    "        x = self.upsample(x)\n",
    "        return x\n",
    "\n",
    "# %%\n",
    "# Cell 5: Evaluation function\n",
    "def evaluate_model(model, dataloader):\n",
    "    model.eval()\n",
    "    psnr_total = 0\n",
    "    ssim_total = 0\n",
    "    count = 0\n",
    "    with torch.no_grad():\n",
    "        for lr, hr in dataloader:\n",
    "            lr = lr.to(device)\n",
    "            hr = hr.to(device)\n",
    "            sr = model(lr)\n",
    "            # Convert tensors to numpy arrays\n",
    "            sr_np = sr.cpu().numpy()\n",
    "            hr_np = hr.cpu().numpy()\n",
    "            for i in range(sr_np.shape[0]):\n",
    "                sr_img = np.squeeze(sr_np[i])\n",
    "                hr_img = np.squeeze(hr_np[i])\n",
    "                # Convert [0,1] range if needed\n",
    "                psnr = peak_signal_noise_ratio(hr_img, sr_img, data_range=1)\n",
    "                ssim = structural_similarity(hr_img, sr_img, data_range=1)\n",
    "                psnr_total += psnr\n",
    "                ssim_total += ssim\n",
    "                count += 1\n",
    "    print(f\"Average PSNR: {psnr_total/count:.2f}\")\n",
    "    print(f\"Average SSIM: {ssim_total/count:.4f}\")\n",
    "\n",
    "# %%\n",
    "# Cell 6: Data loading\n",
    "folder = 'Ir'  # Update this path to your dataset location\n",
    "dataset = InfraredDataset(folder, scale=4, crop_size=512)\n",
    "dataloader = DataLoader(dataset, batch_size=16, shuffle=True)\n",
    "\n",
    "# %%\n",
    "# Cell 7: SRCNN Model training and evaluation\n",
    "print(\"Training SRCNN model...\")\n",
    "srcnn_model = SRCNN().to(device)\n",
    "criterion = nn.MSELoss()\n",
    "optimizer = optim.Adam(srcnn_model.parameters(), lr=1e-4)\n",
    "\n",
    "num_epochs = 10\n",
    "for epoch in range(num_epochs):\n",
    "    srcnn_model.train()\n",
    "    total_loss = 0\n",
    "    for i, (lr, hr) in enumerate(dataloader):\n",
    "        lr, hr = lr.to(device), hr.to(device)\n",
    "        \n",
    "        optimizer.zero_grad()\n",
    "        sr = srcnn_model(lr)\n",
    "        loss = criterion(sr, hr)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        \n",
    "        total_loss += loss.item()\n",
    "        \n",
    "        if i % 10 == 0:\n",
    "            print(f\"Epoch {epoch+1}/{num_epochs}, Batch {i}, Loss: {loss.item():.4f}\")\n",
    "    \n",
    "    avg_loss = total_loss / len(dataloader)\n",
    "    print(f\"Epoch {epoch+1}/{num_epochs}, Average Loss: {avg_loss:.4f}\")\n",
    "\n",
    "# Save the trained model\n",
    "torch.save(srcnn_model.state_dict(), 'srcnn_infrared_model.pth')\n",
    "print(\"SRCNN Model saved as 'srcnn_infrared_model.pth'\")\n",
    "\n",
    "# Evaluate SRCNN model\n",
    "print(\"\\nEvaluating SRCNN model:\")\n",
    "evaluate_model(srcnn_model, dataloader)\n",
    "\n",
    "# %%\n",
    "# Cell 8: EDSR Model training and evaluation\n",
    "print(\"\\nTraining EDSR model...\")\n",
    "edsr_model = EDSR(num_blocks=8, channels=64, scale=2).to(device)\n",
    "criterion = nn.MSELoss()\n",
    "optimizer = optim.Adam(edsr_model.parameters(), lr=1e-4)\n",
    "\n",
    "num_epochs = 10\n",
    "for epoch in range(num_epochs):\n",
    "    edsr_model.train()\n",
    "    total_loss = 0\n",
    "    for i, (lr, hr) in enumerate(dataloader):\n",
    "        lr, hr = lr.to(device), hr.to(device)\n",
    "        \n",
    "        optimizer.zero_grad()\n",
    "        sr = edsr_model(lr)\n",
    "        loss = criterion(sr, hr)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        \n",
    "        total_loss += loss.item()\n",
    "        \n",
    "        if i % 10 == 0:\n",
    "            print(f\"Epoch {epoch+1}/{num_epochs}, Batch {i}, Loss: {loss.item():.4f}\")\n",
    "    \n",
    "    avg_loss = total_loss / len(dataloader)\n",
    "    print(f\"Epoch {epoch+1}/{num_epochs}, Average Loss: {avg_loss:.4f}\")\n",
    "\n",
    "# Save the trained model\n",
    "torch.save(edsr_model.state_dict(), 'edsr_infrared_model.pth')\n",
    "print(\"EDSR Model saved as 'edsr_infrared_model.pth'\")\n",
    "\n",
    "# Evaluate EDSR model\n",
    "print(\"\\nEvaluating EDSR model:\")\n",
    "evaluate_model(edsr_model, dataloader)\n",
    "\n",
    "# %%\n",
    "# Cell 9: Comparison visualization\n",
    "def compare_models(models, model_names, dataloader):\n",
    "    # Get a sample batch\n",
    "    lr_batch, hr_batch = next(iter(dataloader))\n",
    "    lr = lr_batch[0:1].to(device)  # First image in batch\n",
    "    hr = hr_batch[0:1].to(device)\n",
    "    \n",
    "    # Create subplots\n",
    "    fig, axes = plt.subplots(1, 2 + len(models), figsize=(15, 5))\n",
    "    \n",
    "    # Show LR image\n",
    "    axes[0].imshow(lr.cpu().squeeze(), cmap='gray')\n",
    "    axes[0].set_title('Low Resolution')\n",
    "    axes[0].axis('off')\n",
    "    \n",
    "    # Show HR image\n",
    "    axes[1].imshow(hr.cpu().squeeze(), cmap='gray')\n",
    "    axes[1].set_title('High Resolution')\n",
    "    axes[1].axis('off')\n",
    "    \n",
    "    # Show model outputs\n",
    "    for i, (model, name) in enumerate(zip(models, model_names)):\n",
    "        with torch.no_grad():\n",
    "            sr = model(lr).cpu().squeeze()\n",
    "        \n",
    "        axes[i+2].imshow(sr, cmap='gray')\n",
    "        axes[i+2].set_title(f'{name} Output')\n",
    "        axes[i+2].axis('off')\n",
    "    \n",
    "    plt.tight_layout()\n",
    "    plt.savefig('model_comparison.png')\n",
    "    plt.show()\n",
    "\n",
    "# Compare the models\n",
    "print(\"\\nComparing models visually...\")\n",
    "models = [srcnn_model, edsr_model]\n",
    "model_names = ['SRCNN', 'EDSR']\n",
    "compare_models(models, model_names, dataloader)\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
